version: "3.8"
services:
  app:
    image: mediporta
    build:
      tags: 
        - mediporta
      context: ./Mediporta Rekrutacja
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: admin
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: password
    ports:
      - "9091:8080"

  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./initializationScripts:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:8.4
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password