CREATE TABLE IF NOT EXISTS public.tag
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default",
    count integer,
    CONSTRAINT tag_pkey PRIMARY KEY (id)
)